### ISSUE TITLE
data_extraction_classification and data_featurization modules missing

### ISSUE THREAD

**Issue by JoonatanL** [olivettigroup/interpretable-condition-prediction#1]
I was trying to run the jupyter notebooks to reproduce the data, but keep getting stuck with the same two import problems: 
from data_extraction_rxn_classification import *
from data_featurization import *

These modules don't seem to be present within the repo? Could they be uploaded?

**Comment by chriskarpovich** [comment]
Hi Joonatan, I uploaded those modules and a few other data files that you might need to get it up and running. Let me know if you run into any more issues, thanks!

**Comment by JoonatanL** [comment]
Thanks! I'll look through these over the next few days. I think it looks like everything is there, but I'll let you know if any unexpected issues arise!

**Comment by Keisuke-Koga** [comment]
・ss_extracted_NO_IMPUTATION_precs_all_targets.pkl
This module don't seem to be present within the repo? Could you please confirm that this data is not included as well?

**Comment by chriskarpovich** [comment]
> ・ss_extracted_NO_IMPUTATION_precs_all_targets.pkl This module don't seem to be present within the repo? Could you please confirm that this data is not included as well?

You have to generate that file using this generator script, starting with the initial data file: https://github.com/olivettigroup/interpretable-condition-prediction/blob/417e6772f2c364e1a17af01256ef2b5b3c4851ea/data_extraction_featurization/featurize_temps_cvae_NO_IMPUTATION_precs_all_targets.ipynb

**Comment by Keisuke-Koga** [comment]
Thank you for your response. I tried to run it, but it gave me a ”NameError: name 'imputed_papers' is not defined ”　and I could not generate it.

**Comment by Keisuke-Koga** [comment]
Thank you for your response. I tried to generate it, but in the code to display the density distribution of solid state temperature in the file you answered, I got a NameError: name 'imputed_papers' is not defined, so I could not see the solid state temperature distribution.

**Comment by chriskarpovich** [comment]
That plot was a legacy plot that should not have been in that notebook, thanks for pointing it out. I removed the plot, and I also directly uploaded the data files `ss_extracted_NO_IMPUTATION_precs_all_targets.pkl` and `sg_extracted_NO_IMPUTATION_precs_all_targets.pkl` to the `supplementary_data` folder for you to use so you don't have to process the data yourself with that notebook.
